[ldap]
ldap.fluendo.com ansible_user=user ansible_become=true ansible_become_method=sudo ansible_ssh_private_key_file=/path/to/ssh_key

[bitbucket]
bitbucket.org

[github]
github.com

[jira]
jira.com

[metabase]
metabase.fluendo.com

[google_apps]
google.com
