- name: Actualizar contraseñas compartidas
  hosts: localhost
  vars_files:
    - shared_passwords.yml
  tasks:
    - name: Genera nuevas contraseñas
      set_fact:
        new_password: "{{ random_password }}"
      vars:
        random_password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') }}"
      run_once: true

    - name: Actualizar contraseñas
      uri:
        url: "{{ syspass_url }}/api.php?action=updatepassword"
        method: POST
        body_format: json
        body:
          name: "{{ item.name }}"
          password: "{{ new_password }}"
      with_items: "{{ passwords }}"
